# Generated by Django 2.1.3 on 2018-11-24 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='public',
        ),
    ]
