# Generated by Django 2.1.2 on 2018-11-25 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_message_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='likes',
        ),
    ]
